# Generated by Django 5.2.12 on 2026-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('specilazation', models.CharField(max_length=100)),
                ('rating', models.FloatField(max_length=5)),
            ],
        ),
    ]
